#!/usr/bin/env python3
"""Generate MISSING-ENGINE-RECIPES.md — the cross-KB 'to-prove' backlog.

Every engine_recipe_ref in training-knowledge that doesn't resolve to a current tensor-engine
recipe = a training engine KB #4 expects but the rig hasn't stood up + measured yet. Grouped by
missing engine recipe, with the requesting technique(s) + lane. The seam closes itself as each
engine gets a tensor-engine recipe (hands-on wave). Read-only; regenerate after any change.

Run:  $env:PYTHONUTF8='1'; python recipes/_gen_backlog.py
"""
import os, re, sqlite3
from collections import defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))
ENGINES_DB = os.path.join(os.path.dirname(HERE), "engines.db")
TRAINING_DB = os.path.join(os.path.dirname(os.path.dirname(HERE)), "training-knowledge", "training.db")
OUT = os.path.join(HERE, "MISSING-ENGINE-RECIPES.md")
SLUG = re.compile(r'[a-z0-9][a-z0-9-]{6,}')

def parse_refs(ref):
    if not ref: return []
    m = re.search(r'\((?:primary[^:]*)?:?\s*also:\s*(.*?)\)', ref, re.I) or re.search(r'\(primary[^:]*:\s*(.*?)\)', ref, re.I)
    main, extra = ref, []
    if m: extra = re.split(r'[;,]', m.group(1)); main = ref[:m.start()]
    out = []
    for c in [main] + extra:
        c = c.split('@')[0].strip().strip('(),;. ')
        if c and SLUG.fullmatch(c): out.append(c)
        else:
            toks = SLUG.findall(c)
            if toks: out.append(max(toks, key=len))
    seen, res = set(), []
    for s in out:
        if s not in seen: seen.add(s); res.append(s)
    return res

tk = sqlite3.connect(f"file:{TRAINING_DB}?mode=ro", uri=True)
cats = {cid: slug for cid, slug in tk.execute("select id, slug from categories")}
techs = tk.execute("select slug, name, category_id, engine_recipe_ref from techniques where engine_recipe_ref is not null and engine_recipe_ref<>''").fetchall()
tk.close()
con = sqlite3.connect(f"file:{ENGINES_DB}?mode=ro", uri=True)
rset = {s for (s,) in con.execute("select slug from recipes")}
con.close()

missing = defaultdict(list)   # engine_recipe_slug -> [(tech_name, lane)]
for tslug, tname, tcat_id, ref in techs:
    for cand in parse_refs(ref):
        if cand not in rset:
            missing[cand].append((tname, cats.get(tcat_id, "")))

lines = []
lines.append("# Missing engine recipes — cross-KB backlog (training-knowledge → tensor-engine)\n")
lines.append("> Generated by `recipes/_gen_backlog.py` from KB #4 `engine_recipe_ref`s that don't resolve\n"
             "> to a current tensor-engine recipe. **Not broken — KB #4 is ahead of the rig.** Each row is a\n"
             "> training engine to stand up + measure on the 5090, after which its tensor-engine recipe makes\n"
             "> the cross-KB link resolve automatically. The dangling list *is* the to-prove list.\n")
lines.append(f"\n**{len(missing)} engine recipes referenced by KB #4 but not yet in tensor-engine:**\n")
lines.append("| Missing tensor-engine recipe (expected slug) | Requested by KB #4 technique | Lane |")
lines.append("|---|---|---|")
for slug in sorted(missing):
    reqs = missing[slug]
    first = True
    for tname, lane in reqs:
        if first:
            lines.append(f"| `{slug}` | {tname} | {lane} |")
            first = False
        else:
            lines.append(f"| ↳ | {tname} | {lane} |")
lines.append("")
with open(OUT, "w", encoding="utf-8") as f:
    f.write("\n".join(lines))
print(f"wrote {OUT}")
print(f"{len(missing)} missing engine recipes, referenced by {sum(len(v) for v in missing.values())} technique-edges")
